#requires -Version 7.0
<#
.SYNOPSIS
    Populate tests/Engine.Tests/fixtures/ with canonical decoder test images.

.DESCRIPTION
    Synthetic fixtures (png, bmp, gif, tiff) are generated by the inline C#
    helper below.  Compressed-format fixtures (webp, avif, heic, icc-jpg) are
    fetched from upstream test suites.  Idempotent unless -Force is passed.
#>
[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$fixturesDir = $PSScriptRoot
Write-Host "==> fixtures dir: $fixturesDir"

Add-Type -TypeDefinition @'
using System;
using System.IO;
using System.IO.Compression;
using System.Text;

public static class FixtureGen {
    private static readonly uint[] CrcTable;
    static FixtureGen() {
        CrcTable = new uint[256];
        for (uint i = 0; i < 256; i++) {
            uint c = i;
            for (int k = 0; k < 8; k++) c = (c & 1) != 0 ? 0xEDB88320u ^ (c >> 1) : c >> 1;
            CrcTable[i] = c;
        }
    }
    private static uint Crc32(byte[] data) {
        uint c = 0xFFFFFFFF;
        for (int i = 0; i < data.Length; i++) c = CrcTable[(c ^ data[i]) & 0xFF] ^ (c >> 8);
        return c ^ 0xFFFFFFFF;
    }
    private static byte[] Concat(params byte[][] arrs) {
        int n = 0; foreach (var a in arrs) n += a.Length;
        var r = new byte[n]; int p = 0;
        foreach (var a in arrs) { Buffer.BlockCopy(a, 0, r, p, a.Length); p += a.Length; }
        return r;
    }
    private static byte[] Be(uint v) => new byte[] { (byte)(v >> 24), (byte)(v >> 16), (byte)(v >> 8), (byte)v };
    private static byte[] Le16(ushort v) => new byte[] { (byte)v, (byte)(v >> 8) };
    private static byte[] Le32(uint v) => new byte[] { (byte)v, (byte)(v >> 8), (byte)(v >> 16), (byte)(v >> 24) };

    public static void WritePng(string path) {
        // 8x8 RGBA gradient
        var raw = new MemoryStream();
        for (int y = 0; y < 8; y++) {
            raw.WriteByte(0); // filter: none
            for (int x = 0; x < 8; x++) {
                raw.WriteByte((byte)(x * 32));
                raw.WriteByte((byte)(y * 32));
                raw.WriteByte(128);
                raw.WriteByte(255);
            }
        }
        var rawBytes = raw.ToArray();
        // zlib = 0x78 0x9C + deflate + adler32
        var z = new MemoryStream();
        z.WriteByte(0x78); z.WriteByte(0x9C);
        using (var ds = new DeflateStream(z, CompressionLevel.Optimal, true)) ds.Write(rawBytes, 0, rawBytes.Length);
        uint a = 1, b = 0;
        for (int i = 0; i < rawBytes.Length; i++) { a = (a + rawBytes[i]) % 65521u; b = (b + a) % 65521u; }
        var adler = new byte[] { (byte)(b >> 8), (byte)b, (byte)(a >> 8), (byte)a };
        z.Write(adler, 0, 4);
        var idat = z.ToArray();

        byte[] Chunk(string type, byte[] data) {
            var typeBytes = Encoding.ASCII.GetBytes(type);
            var crc = Crc32(Concat(typeBytes, data));
            return Concat(Be((uint)data.Length), typeBytes, data, Be(crc));
        }
        var ihdr = Concat(Be(8), Be(8), new byte[] { 8, 6, 0, 0, 0 });
        var sig = new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A };
        File.WriteAllBytes(path, Concat(sig, Chunk("IHDR", ihdr), Chunk("IDAT", idat), Chunk("IEND", new byte[0])));
    }

    public static void WriteBmp(string path) {
        var pixels = new MemoryStream();
        for (int y = 7; y >= 0; y--)  // BMP bottom-up
            for (int x = 0; x < 8; x++) {
                pixels.WriteByte(128);
                pixels.WriteByte((byte)(y * 32));
                pixels.WriteByte((byte)(x * 32));
            }
        var px = pixels.ToArray();
        uint size = (uint)(14 + 40 + px.Length);
        var ms = new MemoryStream();
        var bw = new BinaryWriter(ms);
        bw.Write(new byte[] { (byte)'B', (byte)'M' });
        bw.Write(size); bw.Write((ushort)0); bw.Write((ushort)0); bw.Write((uint)54);
        bw.Write((uint)40); bw.Write(8); bw.Write(8);
        bw.Write((ushort)1); bw.Write((ushort)24);
        bw.Write((uint)0); bw.Write((uint)px.Length);
        bw.Write(2835); bw.Write(2835);
        bw.Write((uint)0); bw.Write((uint)0);
        bw.Write(px);
        File.WriteAllBytes(path, ms.ToArray());
    }

    public static void WriteGif(string path) {
        using var ms = new MemoryStream();
        using var bw = new BinaryWriter(ms);
        bw.Write(Encoding.ASCII.GetBytes("GIF89a"));
        bw.Write((ushort)8); bw.Write((ushort)8);
        bw.Write((byte)0xF1); bw.Write((byte)0); bw.Write((byte)0);
        // 4-entry palette
        bw.Write(new byte[] { 255,0,0, 0,255,0, 0,0,255, 0,0,0 });
        // NETSCAPE2.0 looping extension
        bw.Write(new byte[] { 0x21, 0xFF, 11 });
        bw.Write(Encoding.ASCII.GetBytes("NETSCAPE2.0"));
        bw.Write(new byte[] { 3, 1, 0, 0, 0 });
        for (int f = 0; f < 2; f++) {
            bw.Write(new byte[] { 0x21, 0xF9, 4, 0x04 });
            bw.Write((ushort)10); bw.Write((byte)0); bw.Write((byte)0);
            bw.Write((byte)0x2C);
            bw.Write((ushort)0); bw.Write((ushort)0); bw.Write((ushort)8); bw.Write((ushort)8);
            bw.Write((byte)0);
            bw.Write((byte)2); // LZW min code size
            // Hand-pack 3-bit codes: clear(4), 64x f, EOI(5)
            int[] codes = new int[66];
            codes[0] = 4;
            for (int i = 0; i < 64; i++) codes[i + 1] = f;
            codes[65] = 5;
            var packed = new MemoryStream();
            int bits = 0, acc = 0;
            foreach (var c in codes) {
                acc |= c << bits; bits += 3;
                while (bits >= 8) { packed.WriteByte((byte)(acc & 0xFF)); acc >>= 8; bits -= 8; }
            }
            if (bits > 0) packed.WriteByte((byte)(acc & 0xFF));
            var pk = packed.ToArray();
            bw.Write((byte)pk.Length);
            bw.Write(pk);
            bw.Write((byte)0);
        }
        bw.Write((byte)0x3B);
        File.WriteAllBytes(path, ms.ToArray());
    }

    public static void WriteTiff(string path) {
        var s1 = new MemoryStream();
        var s2 = new MemoryStream();
        for (int y = 0; y < 8; y++)
            for (int x = 0; x < 8; x++) {
                s1.WriteByte((byte)(x * 32)); s1.WriteByte(0); s1.WriteByte(0);
                s2.WriteByte(0); s2.WriteByte((byte)(y * 32)); s2.WriteByte(0);
            }
        var a = s1.ToArray();
        var b = s2.ToArray();

        using var ms = new MemoryStream();
        using var bw = new BinaryWriter(ms);
        // Header: II 42 offset
        bw.Write(Encoding.ASCII.GetBytes("II"));
        bw.Write((ushort)42);
        // Strips live at offset 8..8+a.Length..8+a.Length+b.Length
        uint stripsEnd = (uint)(8 + a.Length + b.Length);
        bw.Write(stripsEnd);                // offset to IFD0
        bw.Write(a);
        bw.Write(b);

        void WriteIfd(uint stripOffset, uint stripLen, uint next) {
            bw.Write((ushort)8);
            void Tag(ushort tag, ushort type, uint count, uint val) {
                bw.Write(tag); bw.Write(type); bw.Write(count); bw.Write(val);
            }
            Tag(256, 3, 1, 8);
            Tag(257, 3, 1, 8);
            Tag(258, 3, 1, 8);
            Tag(259, 3, 1, 1);
            Tag(262, 3, 1, 2);
            Tag(273, 4, 1, stripOffset);
            Tag(277, 3, 1, 3);
            Tag(279, 4, 1, stripLen);
            bw.Write(next);
        }
        uint ifd0 = stripsEnd;
        uint ifdSize = (uint)(2 + 8 * 12 + 4);
        uint ifd1 = ifd0 + ifdSize;
        WriteIfd(8, (uint)a.Length, ifd1);
        WriteIfd((uint)(8 + a.Length), (uint)b.Length, 0);
        File.WriteAllBytes(path, ms.ToArray());
    }
}
'@ -Language CSharp

function Skip-IfPresent {
    param([string]$Path)
    if ((Test-Path $Path) -and -not $Force) { Write-Host "    skip (exists): $(Split-Path -Leaf $Path)"; return $true }
    return $false
}

function Save-Url {
    param([string]$Url, [string]$Path)
    if (Skip-IfPresent $Path) { return }
    try {
        Invoke-WebRequest -Uri $Url -OutFile $Path -UseBasicParsing -ErrorAction Stop -TimeoutSec 30
        $size = (Get-Item $Path).Length
        Write-Host "    fetched: $(Split-Path -Leaf $Path) ($size B) from $Url"
    } catch {
        Write-Warning "    fetch failed for $Url -- $_"
    }
}

$png = Join-Path $fixturesDir 'sample.png'
$bmp = Join-Path $fixturesDir 'sample.bmp'
$gif = Join-Path $fixturesDir 'sample-animated.gif'
$tif = Join-Path $fixturesDir 'sample-multipage.tiff'

if (-not (Skip-IfPresent $png)) { [FixtureGen]::WritePng($png);  Write-Host "    created: $(Split-Path -Leaf $png) ($((Get-Item $png).Length)B)" }
if (-not (Skip-IfPresent $bmp)) { [FixtureGen]::WriteBmp($bmp);  Write-Host "    created: $(Split-Path -Leaf $bmp) ($((Get-Item $bmp).Length)B)" }
if (-not (Skip-IfPresent $gif)) { [FixtureGen]::WriteGif($gif);  Write-Host "    created: $(Split-Path -Leaf $gif) ($((Get-Item $gif).Length)B)" }
if (-not (Skip-IfPresent $tif)) { [FixtureGen]::WriteTiff($tif); Write-Host "    created: $(Split-Path -Leaf $tif) ($((Get-Item $tif).Length)B)" }

# Upstream samples (permissive licenses — redistributable for testing)
Save-Url 'https://www.gstatic.com/webp/gallery/1.sm.webp'                                                            (Join-Path $fixturesDir 'sample.webp')
Save-Url 'https://raw.githubusercontent.com/link-u/avif-sample-images/master/fox.profile0.8bpc.yuv420.avif'           (Join-Path $fixturesDir 'sample.avif')
Save-Url 'https://github.com/strukturag/libheif/raw/master/examples/example.heic'                                    (Join-Path $fixturesDir 'sample.heic')
Save-Url 'https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_2.jpg'                (Join-Path $fixturesDir 'sample-with-icc.jpg')

Write-Host ""
Write-Host "==> fixtures present:"
Get-ChildItem $fixturesDir -File | Where-Object { $_.Name -ne 'fetch-fixtures.ps1' -and $_.Name -ne 'README.md' } | Format-Table Name, Length -AutoSize
